/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CODEGEN_PREFIX
  #define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
  #define _NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) Simulate_system_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[7] = {3, 1, 0, 3, 0, 1, 2};

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, nnz, is_sparse, c, k;
  const casadi_int *colind, *row;
  size_t p_nrow, p_ncol;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  nnz = sp[ncol];
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  if (is_sparse) {
#ifndef CASADI_MEX_NO_SPARSE
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
#else /* CASADI_MEX_NO_SPARSE */
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Sparse inputs disabled.");
#endif /* CASADI_MEX_NO_SPARSE */
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch.");
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, nnz, c, k;
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  nnz = sp[ncol];
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

/* Simulate_system:(states[6],controls,params[3])->(xf[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a4, a5, a6, a7, a8, a9;
  a0=arg[0] ? arg[0][0] : 0;
  a1=4.1666666666666669e-004;
  a2=arg[0] ? arg[0][1] : 0;
  a3=2.;
  a4=1.2500000000000000e-003;
  a5=arg[2] ? arg[2][2] : 0;
  a6=4000000.;
  a7=casadi_sq(a0);
  a7=(a6*a7);
  a8=800.;
  a7=(a7+a8);
  a9=67.;
  a7=(a7/a9);
  a7=(a7*a2);
  a10=10000000.;
  a11=casadi_sq(a0);
  a11=(a10*a11);
  a12=100.;
  a11=(a11+a12);
  a11=(a11*a0);
  a11=(a11/a9);
  a7=(a7+a11);
  a7=(a5-a7);
  a11=4.9050000000000000e+002;
  a13=arg[2] ? arg[2][1] : 0;
  a11=(a11*a13);
  a11=(a11/a9);
  a7=(a7+a11);
  a13=1000.;
  a14=arg[0] ? arg[0][2] : 0;
  a15=(a13*a14);
  a15=(a15/a9);
  a7=(a7-a15);
  a15=(a4*a7);
  a15=(a2+a15);
  a16=(a3*a15);
  a16=(a2+a16);
  a17=(a4*a2);
  a17=(a0+a17);
  a18=casadi_sq(a17);
  a18=(a6*a18);
  a18=(a18+a8);
  a18=(a18/a9);
  a18=(a18*a15);
  a19=casadi_sq(a17);
  a19=(a10*a19);
  a19=(a19+a12);
  a19=(a19*a17);
  a19=(a19/a9);
  a18=(a18+a19);
  a18=(a5-a18);
  a18=(a18+a11);
  a19=fabs(a2);
  a19=(a19*a14);
  a20=30.;
  a21=3.1830988618379069e-001;
  a22=9.8480775301220802e-001;
  a23=arg[2] ? arg[2][0] : 0;
  a23=(a9*a23);
  a22=(a22*a23);
  a23=8.5174431145629327e+001;
  a22=(a22+a23);
  a22=atan(a22);
  a21=(a21*a22);
  a22=5.9999999999999998e-001;
  a21=(a21+a22);
  a20=(a20*a21);
  a22=10.;
  a21=(a22*a21);
  a23=5.0000000000000001e-003;
  a24=(a2/a23);
  a24=casadi_sq(a24);
  a24=(-a24);
  a24=exp(a24);
  a24=(a21*a24);
  a24=(a20+a24);
  a24=(a24/a13);
  a19=(a19/a24);
  a19=(a2-a19);
  a24=(a4*a19);
  a24=(a14+a24);
  a25=(a13*a24);
  a25=(a25/a9);
  a18=(a18-a25);
  a25=(a4*a18);
  a25=(a2+a25);
  a26=(a3*a25);
  a16=(a16+a26);
  a26=2.5000000000000001e-003;
  a27=(a4*a15);
  a27=(a0+a27);
  a28=casadi_sq(a27);
  a28=(a6*a28);
  a28=(a28+a8);
  a28=(a28/a9);
  a28=(a28*a25);
  a29=casadi_sq(a27);
  a29=(a10*a29);
  a29=(a29+a12);
  a29=(a29*a27);
  a29=(a29/a9);
  a28=(a28+a29);
  a28=(a5-a28);
  a28=(a28+a11);
  a29=fabs(a15);
  a29=(a29*a24);
  a24=(a15/a23);
  a24=casadi_sq(a24);
  a24=(-a24);
  a24=exp(a24);
  a24=(a21*a24);
  a24=(a20+a24);
  a24=(a24/a13);
  a29=(a29/a24);
  a29=(a15-a29);
  a24=(a4*a29);
  a24=(a14+a24);
  a30=(a13*a24);
  a30=(a30/a9);
  a28=(a28-a30);
  a30=(a26*a28);
  a30=(a2+a30);
  a16=(a16+a30);
  a16=(a1*a16);
  a16=(a0+a16);
  a18=(a3*a18);
  a7=(a7+a18);
  a28=(a3*a28);
  a7=(a7+a28);
  a28=(a26*a25);
  a28=(a0+a28);
  a18=casadi_sq(a28);
  a18=(a6*a18);
  a18=(a18+a8);
  a18=(a18/a9);
  a18=(a18*a30);
  a31=casadi_sq(a28);
  a31=(a10*a31);
  a31=(a31+a12);
  a31=(a31*a28);
  a31=(a31/a9);
  a18=(a18+a31);
  a18=(a5-a18);
  a18=(a18+a11);
  a31=fabs(a25);
  a31=(a31*a24);
  a24=(a25/a23);
  a24=casadi_sq(a24);
  a24=(-a24);
  a24=exp(a24);
  a24=(a21*a24);
  a24=(a20+a24);
  a24=(a24/a13);
  a31=(a31/a24);
  a31=(a25-a31);
  a24=(a26*a31);
  a24=(a14+a24);
  a32=(a13*a24);
  a32=(a32/a9);
  a18=(a18-a32);
  a7=(a7+a18);
  a7=(a1*a7);
  a7=(a2+a7);
  a18=casadi_sq(a16);
  a18=(a6*a18);
  a18=(a18+a8);
  a18=(a18/a9);
  a18=(a18*a7);
  a32=casadi_sq(a16);
  a32=(a10*a32);
  a32=(a32+a12);
  a32=(a32*a16);
  a32=(a32/a9);
  a18=(a18+a32);
  a18=(a5-a18);
  a18=(a18+a11);
  a29=(a3*a29);
  a19=(a19+a29);
  a31=(a3*a31);
  a19=(a19+a31);
  a31=fabs(a30);
  a31=(a31*a24);
  a24=(a30/a23);
  a24=casadi_sq(a24);
  a24=(-a24);
  a24=exp(a24);
  a24=(a21*a24);
  a24=(a20+a24);
  a24=(a24/a13);
  a31=(a31/a24);
  a31=(a30-a31);
  a19=(a19+a31);
  a19=(a1*a19);
  a14=(a14+a19);
  a19=(a13*a14);
  a19=(a19/a9);
  a18=(a18-a19);
  a19=(a4*a18);
  a19=(a7+a19);
  a31=(a3*a19);
  a31=(a7+a31);
  a24=(a4*a7);
  a24=(a16+a24);
  a29=casadi_sq(a24);
  a29=(a6*a29);
  a29=(a29+a8);
  a29=(a29/a9);
  a29=(a29*a19);
  a32=casadi_sq(a24);
  a32=(a10*a32);
  a32=(a32+a12);
  a32=(a32*a24);
  a32=(a32/a9);
  a29=(a29+a32);
  a29=(a5-a29);
  a29=(a29+a11);
  a32=fabs(a7);
  a32=(a32*a14);
  a33=(a7/a23);
  a33=casadi_sq(a33);
  a33=(-a33);
  a33=exp(a33);
  a33=(a21*a33);
  a33=(a20+a33);
  a33=(a33/a13);
  a32=(a32/a33);
  a32=(a7-a32);
  a33=(a4*a32);
  a33=(a14+a33);
  a34=(a13*a33);
  a34=(a34/a9);
  a29=(a29-a34);
  a34=(a4*a29);
  a34=(a7+a34);
  a35=(a3*a34);
  a31=(a31+a35);
  a35=(a4*a19);
  a35=(a16+a35);
  a36=casadi_sq(a35);
  a36=(a6*a36);
  a36=(a36+a8);
  a36=(a36/a9);
  a36=(a36*a34);
  a37=casadi_sq(a35);
  a37=(a10*a37);
  a37=(a37+a12);
  a37=(a37*a35);
  a37=(a37/a9);
  a36=(a36+a37);
  a36=(a5-a36);
  a36=(a36+a11);
  a37=fabs(a19);
  a37=(a37*a33);
  a33=(a19/a23);
  a33=casadi_sq(a33);
  a33=(-a33);
  a33=exp(a33);
  a33=(a21*a33);
  a33=(a20+a33);
  a33=(a33/a13);
  a37=(a37/a33);
  a37=(a19-a37);
  a33=(a4*a37);
  a33=(a14+a33);
  a38=(a13*a33);
  a38=(a38/a9);
  a36=(a36-a38);
  a38=(a26*a36);
  a38=(a7+a38);
  a31=(a31+a38);
  a31=(a1*a31);
  a31=(a16+a31);
  if (res[0]!=0) res[0][0]=a31;
  a29=(a3*a29);
  a18=(a18+a29);
  a36=(a3*a36);
  a18=(a18+a36);
  a36=(a26*a34);
  a36=(a16+a36);
  a29=casadi_sq(a36);
  a29=(a6*a29);
  a29=(a29+a8);
  a29=(a29/a9);
  a29=(a29*a38);
  a8=casadi_sq(a36);
  a8=(a10*a8);
  a8=(a8+a12);
  a8=(a8*a36);
  a8=(a8/a9);
  a29=(a29+a8);
  a5=(a5-a29);
  a5=(a5+a11);
  a11=fabs(a34);
  a11=(a11*a33);
  a33=(a34/a23);
  a33=casadi_sq(a33);
  a33=(-a33);
  a33=exp(a33);
  a33=(a21*a33);
  a33=(a20+a33);
  a33=(a33/a13);
  a11=(a11/a33);
  a11=(a34-a11);
  a33=(a26*a11);
  a33=(a14+a33);
  a29=(a13*a33);
  a29=(a29/a9);
  a5=(a5-a29);
  a18=(a18+a5);
  a18=(a1*a18);
  a18=(a7+a18);
  if (res[0]!=0) res[0][1]=a18;
  a37=(a3*a37);
  a32=(a32+a37);
  a11=(a3*a11);
  a32=(a32+a11);
  a11=fabs(a38);
  a11=(a11*a33);
  a23=(a38/a23);
  a23=casadi_sq(a23);
  a23=(-a23);
  a23=exp(a23);
  a21=(a21*a23);
  a20=(a20+a21);
  a20=(a20/a13);
  a11=(a11/a20);
  a11=(a38-a11);
  a32=(a32+a11);
  a32=(a1*a32);
  a14=(a14+a32);
  if (res[0]!=0) res[0][2]=a14;
  a14=arg[0] ? arg[0][3] : 0;
  a32=arg[1] ? arg[1][0] : 0;
  a11=(a3*a32);
  a11=(a32+a11);
  a20=(a3*a32);
  a11=(a11+a20);
  a11=(a11+a32);
  a11=(a1*a11);
  a11=(a14+a11);
  a20=(a3*a32);
  a20=(a32+a20);
  a13=(a3*a32);
  a20=(a20+a13);
  a20=(a20+a32);
  a20=(a1*a20);
  a20=(a11+a20);
  if (res[0]!=0) res[0][3]=a20;
  a20=arg[0] ? arg[0][4] : 0;
  a13=-4.7619047619047616e-002;
  a21=(a13*a20);
  a23=casadi_sq(a0);
  a23=(a6*a23);
  a23=(a23*a2);
  a2=casadi_sq(a0);
  a2=(a10*a2);
  a2=(a2*a0);
  a23=(a23+a2);
  a2=1.6000000000000000e-002;
  a23=(a23/a2);
  a21=(a21+a23);
  a23=arg[0] ? arg[0][5] : 0;
  a0=(a22*a23);
  a21=(a21+a0);
  a0=(a4*a21);
  a0=(a20+a0);
  a0=(a13*a0);
  a33=casadi_sq(a17);
  a33=(a6*a33);
  a33=(a33*a15);
  a15=casadi_sq(a17);
  a15=(a10*a15);
  a15=(a15*a17);
  a33=(a33+a15);
  a33=(a33/a2);
  a0=(a0+a33);
  a33=-10.;
  a15=(a33*a23);
  a15=(a15+a14);
  a17=(a4*a15);
  a17=(a23+a17);
  a37=(a22*a17);
  a0=(a0+a37);
  a37=(a3*a0);
  a21=(a21+a37);
  a0=(a4*a0);
  a0=(a20+a0);
  a0=(a13*a0);
  a37=casadi_sq(a27);
  a37=(a6*a37);
  a37=(a37*a25);
  a25=casadi_sq(a27);
  a25=(a10*a25);
  a25=(a25*a27);
  a37=(a37+a25);
  a37=(a37/a2);
  a0=(a0+a37);
  a17=(a33*a17);
  a37=(a4*a32);
  a37=(a14+a37);
  a17=(a17+a37);
  a37=(a4*a17);
  a37=(a23+a37);
  a25=(a22*a37);
  a0=(a0+a25);
  a25=(a3*a0);
  a21=(a21+a25);
  a0=(a26*a0);
  a0=(a20+a0);
  a0=(a13*a0);
  a25=casadi_sq(a28);
  a25=(a6*a25);
  a25=(a25*a30);
  a30=casadi_sq(a28);
  a30=(a10*a30);
  a30=(a30*a28);
  a25=(a25+a30);
  a25=(a25/a2);
  a0=(a0+a25);
  a37=(a33*a37);
  a25=(a4*a32);
  a25=(a14+a25);
  a37=(a37+a25);
  a25=(a26*a37);
  a25=(a23+a25);
  a30=(a22*a25);
  a0=(a0+a30);
  a21=(a21+a0);
  a21=(a1*a21);
  a20=(a20+a21);
  a21=(a13*a20);
  a0=casadi_sq(a16);
  a0=(a6*a0);
  a0=(a0*a7);
  a7=casadi_sq(a16);
  a7=(a10*a7);
  a7=(a7*a16);
  a0=(a0+a7);
  a0=(a0/a2);
  a21=(a21+a0);
  a17=(a3*a17);
  a15=(a15+a17);
  a37=(a3*a37);
  a15=(a15+a37);
  a25=(a33*a25);
  a37=(a26*a32);
  a14=(a14+a37);
  a25=(a25+a14);
  a15=(a15+a25);
  a15=(a1*a15);
  a23=(a23+a15);
  a15=(a22*a23);
  a21=(a21+a15);
  a15=(a4*a21);
  a15=(a20+a15);
  a15=(a13*a15);
  a25=casadi_sq(a24);
  a25=(a6*a25);
  a25=(a25*a19);
  a19=casadi_sq(a24);
  a19=(a10*a19);
  a19=(a19*a24);
  a25=(a25+a19);
  a25=(a25/a2);
  a15=(a15+a25);
  a25=(a33*a23);
  a25=(a25+a11);
  a19=(a4*a25);
  a19=(a23+a19);
  a24=(a22*a19);
  a15=(a15+a24);
  a24=(a3*a15);
  a21=(a21+a24);
  a15=(a4*a15);
  a15=(a20+a15);
  a15=(a13*a15);
  a24=casadi_sq(a35);
  a24=(a6*a24);
  a24=(a24*a34);
  a34=casadi_sq(a35);
  a34=(a10*a34);
  a34=(a34*a35);
  a24=(a24+a34);
  a24=(a24/a2);
  a15=(a15+a24);
  a19=(a33*a19);
  a24=(a4*a32);
  a24=(a11+a24);
  a19=(a19+a24);
  a24=(a4*a19);
  a24=(a23+a24);
  a34=(a22*a24);
  a15=(a15+a34);
  a34=(a3*a15);
  a21=(a21+a34);
  a15=(a26*a15);
  a15=(a20+a15);
  a13=(a13*a15);
  a15=casadi_sq(a36);
  a6=(a6*a15);
  a6=(a6*a38);
  a38=casadi_sq(a36);
  a10=(a10*a38);
  a10=(a10*a36);
  a6=(a6+a10);
  a6=(a6/a2);
  a13=(a13+a6);
  a24=(a33*a24);
  a4=(a4*a32);
  a4=(a11+a4);
  a24=(a24+a4);
  a4=(a26*a24);
  a4=(a23+a4);
  a22=(a22*a4);
  a13=(a13+a22);
  a21=(a21+a13);
  a21=(a1*a21);
  a20=(a20+a21);
  if (res[0]!=0) res[0][4]=a20;
  a19=(a3*a19);
  a25=(a25+a19);
  a3=(a3*a24);
  a25=(a25+a3);
  a33=(a33*a4);
  a26=(a26*a32);
  a11=(a11+a26);
  a33=(a33+a11);
  a25=(a25+a33);
  a1=(a1*a25);
  a23=(a23+a1);
  if (res[0]!=0) res[0][5]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int Simulate_system(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT void Simulate_system_incref(void) {
}

CASADI_SYMBOL_EXPORT void Simulate_system_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int Simulate_system_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int Simulate_system_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_in(casadi_int i){
  switch (i) {
    case 0: return "states";
    case 1: return "controls";
    case 2: return "params";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* Simulate_system_name_out(casadi_int i){
  switch (i) {
    case 0: return "xf";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Simulate_system_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* Simulate_system_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int Simulate_system_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_Simulate_system(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i, j;
  casadi_real w[55];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+16);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+6, casadi_s1, w+16);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+7, casadi_s2, w+16);
  --resc;
  res[0] = w+10;
  i = Simulate_system(arg, res, iw, w+16, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"Simulate_system\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[16];
  int buf_ok = --argc >= 0 && !mxGetString(*argv++, buf, sizeof(buf));
  if (!buf_ok) {
    /* name error */
  } else if (strcmp(buf, "Simulate_system")==0) {
    mex_Simulate_system(resc, resv, argc, argv);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'Simulate_system'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
